---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: set-env
    image: alpine:latest
    commands:
      - export VERSION=$(cat version.txt)
      - export PROJECT_NAME=$(cat project-name.txt)

  - name: build-image
    image: docker:19.03-dind
    commands:
      - echo VERSION
      - echo PROJECT_NAME
      - docker build -t $VERSION:$PROJECT_NAME -f Dockerfile .

  - name: run-tests
    image: $PROJECT_NAME:$VERSION
    commands:
      - poetry install
      - pytest

  - name: run-fastapi-app
    image: $PROJECT_NAME:$VERSION
    commands:
      - docker run -d -p 10087:80 --name $PROJECT_NAME $PROJECT_NAME:$VERSION

