---
kind: pipeline
type: docker
name: python-3-4

steps:
- name: remove old container
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker stop generate-fastapi
  - docker rm generate-fastapi
  - docker rmi generate-fastapi-be:1.0.0