---
kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ls -l
      - docker build -t generate-fastapi-be:1.0.0 .

#  - name: test
#    image: generate-fastapi-be:1.0.0
#    commands:
#      - pytest

  - name: run-container
    image: docker:dind
    commands:
      - docker run -d -p 10087:80 --name generate-fastapi generate-fastapi-be:1.0.0

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
