"""upgrade

Revision ID: d379247f2097
Revises: eaf01db96f72
Create Date: 2024-05-07 18:38:00.565571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd379247f2097'
down_revision: Union[str, None] = 'eaf01db96f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('add_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.create_index(op.f('ix_auth_name'), 'auth', ['name'], unique=False)
    op.create_table('generate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('api_json', sa.JSON(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('add_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generate_id'), 'generate', ['id'], unique=False)
    op.create_index(op.f('ix_generate_module'), 'generate', ['module'], unique=False)
    op.create_index(op.f('ix_generate_project_id'), 'generate', ['project_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('add_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('role_auth_rels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('auth_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('add_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_auth_rels_auth_id'), 'role_auth_rels', ['auth_id'], unique=False)
    op.create_index(op.f('ix_role_auth_rels_id'), 'role_auth_rels', ['id'], unique=False)
    op.create_index(op.f('ix_role_auth_rels_role_id'), 'role_auth_rels', ['role_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('division_id', sa.String(), nullable=True),
    sa.Column('add_datetime', sa.DateTime(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_division_id'), 'user', ['division_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_role_id'), 'user', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_id'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_division_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_auth_rels_role_id'), table_name='role_auth_rels')
    op.drop_index(op.f('ix_role_auth_rels_id'), table_name='role_auth_rels')
    op.drop_index(op.f('ix_role_auth_rels_auth_id'), table_name='role_auth_rels')
    op.drop_table('role_auth_rels')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_generate_project_id'), table_name='generate')
    op.drop_index(op.f('ix_generate_module'), table_name='generate')
    op.drop_index(op.f('ix_generate_id'), table_name='generate')
    op.drop_table('generate')
    op.drop_index(op.f('ix_auth_name'), table_name='auth')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
